name: Continuous Integration Check
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  compile-with-bazel:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile
      run: |
           bazel test //trpc/...
